### ISSUE TITLE
Different way to add project or data map config in yml

### ISSUE THREAD

**Issue by aarrsseni** [bootique/bootique-cayenne#70] opened 2019-08-29 13:13 UTC
Here is example of adding cayenne-project and datamap in one config:
```
cayenne:
  createSchema: true
  datasource: defaultds
  configs:
    - cayenne-project1.xml
  maps:
    - location: classpath:dm1.map.xml
      name: map1
      datasource: ds1
```
To add map we need to set location as `classpath:dm1.map.xml`
To add project we need to set as `cayenne-project1.xml` without `classpath:`
But there are both in the same directory.
We should make common pattern of adding projects or datamap.

**Comment by andrus** [comment] 2019-08-29 13:32
This looks like a duplicate of #17. I am all for doing this, but my concern is about backwards compatibility. I don't see an easy way to deprecate the old format gradually, as ResourceFactory URL format also supports URLs without a "protocol" part, that are resolved as files on the file system.

So perhaps this is a 2.0 change.

**Comment by andrus** [comment] 2019-09-04 11:46
Closing as a duplicate of #17.

**Closed by andrus** 2019-09-04 11:46 UTC
